name: Publish multi-arch Docker images

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                base: [ 'debian:bullseye-20220418-slim', 'debian:buster-20220418-slim', 'ubuntu:focal-20220426' ]
                sourceforge: [ 'Y', 'N' ]
                exclude:
                    - base: 'ubuntu:focal-20220426'
                      sourceforge: 'Y'
                
        steps:
        -
            name: Checkout
            uses: actions/checkout@v2
        -
            name: Set Release Tag
            run: |
                date=$(date '+%Y-%m-%d')
                base="$(cut -d ':' -f2 <<< '${{ matrix.base }}')"
                base="$(cut -d '-' -f1 <<< ${base})"
                squeezelite_version=""
                distro_id=${base}
                if [ "${{ matrix.sourceforge }}" = "Y" ]; \
                    then squeezelite_version="squeezelite-1.9.9-sourceforge-"; \
                else \
                    if [ "${base}" = "bullseye" ]; \
                        then squeezelite_version="squeezelite-1.9.8-"; \
                    else \
                        squeezelite_version="squeezelite-1.8-"; \
                    fi
                fi
                if [ "${base}" = "focal" ]; \
                    then distro_id="focal"; \
                fi
                tags="${{secrets.DOCKER_USERNAME}}/squeezelite:${squeezelite_version}${distro_id},${{secrets.DOCKER_USERNAME}}/squeezelite:${squeezelite_version}${distro_id}-${date}"
                if [ "${base}" = "bullseye" ] && [ "${{ matrix.sourceforge }}" = "Y" ]; then \
                    echo "RELEASE_TAGS=${tags},${{secrets.DOCKER_USERNAME}}/squeezelite:sourceforge-bullseye,${{secrets.DOCKER_USERNAME}}/squeezelite:latest"; \
                elif [ "${base}" = "buster" ] && [ "${{ matrix.sourceforge }}" = "Y" ]; then \
                    echo "RELEASE_TAGS=${tags},${{secrets.DOCKER_USERNAME}}/squeezelite:sourceforge-buster"; \
                elif [ "${base}" = "buster" ] && [ "${{ matrix.sourceforge }}" = "N" ]; then \
                    echo "RELEASE_TAGS=${tags},${{secrets.DOCKER_USERNAME}}/squeezelite:${distro_id},${{secrets.DOCKER_USERNAME}}/squeezelite:stable"; \
                elif [ "${base}" = "bullseye" ] && [ "${{ matrix.sourceforge }}" = "N" ]; then \
                    echo "RELEASE_TAGS=${tags},${{secrets.DOCKER_USERNAME}}/squeezelite:${distro_id}"; \
                elif [ "${base}" = "focal" ] && [ "${{ matrix.sourceforge }}" = "N" ]; then \
                    echo "RELEASE_TAGS=${tags},${{secrets.DOCKER_USERNAME}}/squeezelite:${distro_id}"; \
                else \
                    echo "RELEASE_TAGS=${tags}"; \
                fi \
                >> $GITHUB_ENV
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v1
            with:
                platforms: all
        -
            name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v1
        -
            name: Login to DockerHub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
        -
            name: Build and push
            uses: docker/build-push-action@v2
            with:
                context: .
                build-args: |
                    BASE_IMAGE=${{ matrix.base }}
                    DOWNLOAD_FROM_SOURCEFORGE=${{ matrix.sourceforge }}
                platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
                push: true
                tags: ${{ env.RELEASE_TAGS }}