name: Publish multi-arch Docker images

on:
    push:
        branches:
            - main
        tags:
            - '*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v2
        -
            name: Set Release Tag
            run: |
                if [ "${GITHUB_REF#refs/*/}" = "main" ]; \
                then echo "RELEASE_TAG=latest"; \
                else echo "RELEASE_TAG=${GITHUB_REF#refs/*/}"; fi \
                >> $GITHUB_ENV
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v1
            with:
                platforms: all
        -
            name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v1
        -
            name: Login to DockerHub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
        -
            name: Build and push
            uses: docker/build-push-action@v2
            with:
                context: .
                platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/squeezelite:${{ env.RELEASE_TAG }}
